### ISSUE TITLE
Do not create ".composer" at app root

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox-engine-php#21]
Whenever I run `nanobox dev run`, I end up with a `.composer` directory within my app root. This should not happen of course and the process should use `~/.composer` instead.

**Comment by mbrodala** [comment]
It seems like this was added with [this commit](https://github.com/nanobox-io/nanobox-engine-php/commit/4ad6b3f18ead0d4f12bcff30c90b9d213db1a6e6) but I cannot see a clear requirement for this location.

**Comment by tylerflint** [comment]
@notxarb This is something I've put some thought into as well. @mbrodala just for a bit of background on this, those empty directories are the lib_dirs. Nanobox transparently mounts directories from inside of nanobox for lib_dirs. Unfortunately, in order to mount, the directory needs to exist. 

@notxarb I've been thinking about an alternative because I agree with @mbrodala that this feels weird. I wonder if instead we could put lib_dirs in /data/var/lib_dirs/etc for linking things that would normally go in HOME.

**Comment by notxarb** [comment]
Another option is to split up the lib_dirs into categories depending on if they need to be mounted relative to the app or runtime. We discussed making the user's home directory a symlink to a folder in the build. Or just create the user with the home directory in the build, something like /data/var/home/gonano.

**Comment by notxarb** [comment]
The home folder has been moved to a location that gets bundled up in the build process. This issue is now resolved.

**Comment by mbrodala** [comment]
Thanks a lot. :-)
