### ISSUE TITLE
Support apache 2.4

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-engine-php#44]
As the title says.. no sense forcing everyone to use old software

**Comment by glinton** [comment]
I honestly don't know how many people use/need 2.4 but it seems like it should be supported at some point, even though 2.2 does work great.

**Comment by tylerflint** [comment]
The only concern (and reason we haven't already) it that the .htaccess is not compatible between versions. Most php frameworks that depend on apache, only depend on apache because they leverage an .htacess file. Of those frameworks, most are not compatible with 2.4.

Once we have reason to believe there is full compatibility or that all .htaccess files have been ported across the majority of frameworks, we can definitely get this in.
